version: '3.7'
services:
  postgres:
    image: postgres:16
    container_name: mwro-db 
    environment:
        POSTGRES_USER: mwro
        POSTGRES_PASSWORD: pswd
        POSTGRES_DB: mwro_db
    volumes:
      - postgresdata:/var/lib/postgres
    ports:
      - 5430:5432

volumes: 
    postgresdata: 
      driver: local
