version: "3.7"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        image: mwro_api_image
        container_name: mwro_api_container
        volumes:
            - .:/app
        ports:
            - 3040:3040
        depends_on:
            - postgres
        links:
            - postgres
        networks:
            - mwro_network


    postgres:
        image: postgres:16
        container_name: mwro-db
        environment:
            POSTGRES_USER: mwro
            POSTGRES_PASSWORD: pswd
            POSTGRES_DB: mwro_db
        volumes:
            - postgresdata:/var/lib/postgres
        ports:
            - 5430:5432
        networks:
            - mwro_network

networks:
    mwro_network:
        name: mwro_network

volumes:
    postgresdata:
        driver: local
